// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import Amplify from 'aws-amplify'
import config from './aws-exports'
Amplify.configure(config)

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:8d8e24fe-47ba-45d8-9f44-75e1b48b1012",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_3UqsRWckN",
    "aws_user_pools_web_client_id": "7g1057n1igvpbnvb94hb2hpabo",
    "oauth": {
        "domain": "rnamplify85d16374-85d16374-local.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://",
        "redirectSignOut": "myapp://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
